name: Flutter_build

on:
  push:
    branches:
      - master
    tags:
      - '*'


jobs:
  build:
    name: Build
    env:
      source-directory: ./flutter_seuic_scanner_plugin_sdk 
      example-directory: ./flutter_seuic_scanner_plugin_sdk/example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
          
      # Download all Flutter packages
      - name: Download dependencies
        run: flutter pub get
        #working-directory: ${{env.source-directory}}

      # Build Android version of the example App
      - name: Run Android build
        run: flutter build apk --release
        working-directory: ${{env.example-directory}}
