name: Flutter_build

on:
  push:
    branches:
      - master
    tags:
      - '*'


jobs:
  build:
    name: Build
    env:
      source-directory: ./flutter_seuic_scanner_plugin_sdk 
      example-directory: ./flutter_seuic_scanner_plugin_sdk/example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - run: flutter pub get
      
      - working-directory: ${{env.example-directory}}
      - run: flutter build apk --release --target-platform=android-arm64 --no-shrink
